export const mockData = {
  emotions: [
    { name: '행복한', isChecked: true },
    { name: '그리움', isChecked: false },
    { name: '답답한', isChecked: false },
    { name: '만족스러운', isChecked: true },
    { name: '기쁜', isChecked: true },
    { name: '당황한', isChecked: false },
    { name: '억울한', isChecked: false },
    { name: '부러운', isChecked: false },
    { name: '두려운', isChecked: true },
    { name: '서운한', isChecked: false },
    { name: '원망스러운', isChecked: false },
  ],
  topics: [
    { name: '학교', isChecked: false },
    { name: '수업', isChecked: true },
    { name: '친구', isChecked: true },
    { name: '점심', isChecked: true },
    { name: '노래', isChecked: false },
    { name: '학식', isChecked: true },
    { name: '동아리', isChecked: true },
    { name: '과제', isChecked: false },
    { name: '기숙사', isChecked: false },
    { name: '팀플', isChecked: false },
    { name: '축구', isChecked: false },
    { name: '김민재', isChecked: false },
  ],
};
